name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js from .tool-versions
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: "npm"
      - run: npm ci
      - run: npm run typecheck
      - run: npm run format:check
      - run: npm test
      - run: npm run coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
